updated configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -928,8 +928,8 @@ DOC_USER_FORMATS
 ENABLE_SK_TRUE
 ENABLE_SK_FALSE
 DISTCHECK_CONFIGURE_FLAGS
-HAVE_GNOME_DOC_UTILS_TRUE
-HAVE_GNOME_DOC_UTILS_FALSE
+HAVE_MATE_DOC_UTILS_TRUE
+HAVE_MATE_DOC_UTILS_FALSE
 IWLIB
 LIBOBJS
 LTLIBOBJS'
@@ -22908,12 +22908,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_NETSPEED_CFLAGS="$NETSPEED_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libpanelapplet-2.0 libgtop-2.0 >= 2.14.2\"") >&5
-  ($PKG_CONFIG --exists --print-errors "libpanelapplet-2.0 libgtop-2.0 >= 2.14.2") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libmatepanelapplet-2.0 libgtop-2.0 >= 2.14.2\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libmatepanelapplet-2.0 libgtop-2.0 >= 2.14.2") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_NETSPEED_CFLAGS=`$PKG_CONFIG --cflags "libpanelapplet-2.0 libgtop-2.0 >= 2.14.2" 2>/dev/null`
+  pkg_cv_NETSPEED_CFLAGS=`$PKG_CONFIG --cflags "libmatepanelapplet-2.0 libgtop-2.0 >= 2.14.2" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -22926,12 +22926,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_NETSPEED_LIBS="$NETSPEED_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libpanelapplet-2.0 libgtop-2.0 >= 2.14.2\"") >&5
-  ($PKG_CONFIG --exists --print-errors "libpanelapplet-2.0 libgtop-2.0 >= 2.14.2") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libmatepanelapplet-2.0 libgtop-2.0 >= 2.14.2\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libmatepanelapplet-2.0 libgtop-2.0 >= 2.14.2") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_NETSPEED_LIBS=`$PKG_CONFIG --libs "libpanelapplet-2.0 libgtop-2.0 >= 2.14.2" 2>/dev/null`
+  pkg_cv_NETSPEED_LIBS=`$PKG_CONFIG --libs "libmatepanelapplet-2.0 libgtop-2.0 >= 2.14.2" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -22950,14 +22950,14 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        NETSPEED_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libpanelapplet-2.0 libgtop-2.0 >= 2.14.2"`
+	        NETSPEED_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libmatepanelapplet-2.0 libgtop-2.0 >= 2.14.2"`
         else
-	        NETSPEED_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libpanelapplet-2.0 libgtop-2.0 >= 2.14.2"`
+	        NETSPEED_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libmatepanelapplet-2.0 libgtop-2.0 >= 2.14.2"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$NETSPEED_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (libpanelapplet-2.0 libgtop-2.0 >= 2.14.2) were not met:
+	{ { echo "$as_me:$LINENO: error: Package requirements (libmatepanelapplet-2.0 libgtop-2.0 >= 2.14.2) were not met:
 
 $NETSPEED_PKG_ERRORS
 
@@ -22968,7 +22968,7 @@ Alternatively, you may set the environment variables NETSPEED_CFLAGS
 and NETSPEED_LIBS to avoid the need to call pkg-config.
 See the pkg-config man page for more details.
 " >&5
-echo "$as_me: error: Package requirements (libpanelapplet-2.0 libgtop-2.0 >= 2.14.2) were not met:
+echo "$as_me: error: Package requirements (libmatepanelapplet-2.0 libgtop-2.0 >= 2.14.2) were not met:
 
 $NETSPEED_PKG_ERRORS
 
@@ -23017,8 +23017,8 @@ fi
 gdu_cv_version_required=0.3.2
 
 if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gnome-doc-utils >= \$gdu_cv_version_required\"") >&5
-  ($PKG_CONFIG --exists --print-errors "gnome-doc-utils >= $gdu_cv_version_required") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"mate-doc-utils >= \$gdu_cv_version_required\"") >&5
+  ($PKG_CONFIG --exists --print-errors "mate-doc-utils >= $gdu_cv_version_required") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
@@ -23030,8 +23030,8 @@ fi
 if test "$gdu_cv_have_gdu" = "yes"; then
 	:
 else
-	{ { echo "$as_me:$LINENO: error: gnome-doc-utils >= $gdu_cv_version_required not found" >&5
-echo "$as_me: error: gnome-doc-utils >= $gdu_cv_version_required not found" >&2;}
+	{ { echo "$as_me:$LINENO: error: mate-doc-utils >= $gdu_cv_version_required not found" >&5
+echo "$as_me: error: mate-doc-utils >= $gdu_cv_version_required not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -23041,7 +23041,7 @@ fi
 if test "${with_help_dir+set}" = set; then
   withval=$with_help_dir;
 else
-  with_help_dir='${datadir}/gnome/help'
+  with_help_dir='${datadir}/mate/help'
 fi
 
 HELP_DIR="$with_help_dir"
@@ -23093,11 +23093,11 @@ DISTCHECK_CONFIGURE_FLAGS="--disable-scrollkeeper $DISTCHECK_CONFIGURE_FLAGS"
 
 
 if test "$gdu_cv_have_gdu" = "yes"; then
-  HAVE_GNOME_DOC_UTILS_TRUE=
-  HAVE_GNOME_DOC_UTILS_FALSE='#'
+  HAVE_MATE_DOC_UTILS_TRUE=
+  HAVE_MATE_DOC_UTILS_FALSE='#'
 else
-  HAVE_GNOME_DOC_UTILS_TRUE='#'
-  HAVE_GNOME_DOC_UTILS_FALSE=
+  HAVE_MATE_DOC_UTILS_TRUE='#'
+  HAVE_MATE_DOC_UTILS_FALSE=
 fi
 
 
@@ -23296,10 +23296,10 @@ echo "$as_me: error: conditional \"ENABLE_SK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${HAVE_GNOME_DOC_UTILS_TRUE}" && test -z "${HAVE_GNOME_DOC_UTILS_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"HAVE_GNOME_DOC_UTILS\" was never defined.
+if test -z "${HAVE_MATE_DOC_UTILS_TRUE}" && test -z "${HAVE_MATE_DOC_UTILS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_MATE_DOC_UTILS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"HAVE_GNOME_DOC_UTILS\" was never defined.
+echo "$as_me: error: conditional \"HAVE_MATE_DOC_UTILS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -24060,8 +24060,8 @@ DOC_USER_FORMATS!$DOC_USER_FORMATS$ac_delim
 ENABLE_SK_TRUE!$ENABLE_SK_TRUE$ac_delim
 ENABLE_SK_FALSE!$ENABLE_SK_FALSE$ac_delim
 DISTCHECK_CONFIGURE_FLAGS!$DISTCHECK_CONFIGURE_FLAGS$ac_delim
-HAVE_GNOME_DOC_UTILS_TRUE!$HAVE_GNOME_DOC_UTILS_TRUE$ac_delim
-HAVE_GNOME_DOC_UTILS_FALSE!$HAVE_GNOME_DOC_UTILS_FALSE$ac_delim
+HAVE_MATE_DOC_UTILS_TRUE!$HAVE_MATE_DOC_UTILS_TRUE$ac_delim
+HAVE_MATE_DOC_UTILS_FALSE!$HAVE_MATE_DOC_UTILS_FALSE$ac_delim
 IWLIB!$IWLIB$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
